version: 2

models: 
  - name: fct_sales
    columns:
      - name: sales_id
        tests:
          - unique
          - not_null
      - name: branch_id
        tests:
          - not_null
      - name: product_id
        tests:
          - not_null
      - name: customer_id
        tests:
          - not_null